---
driver_plugin: vagrant
platforms:
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-centos-6.4.box
  run_list:
- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-centos-5.9.box
  run_list:
suites:
- name: default
  run_list:
  - recipe[sauceproxy]
  attributes: {}
