---
driver_config:
  digitalocean_client_id: <%= ENV['DIGITAL_OCEAN_CLIENT_ID'] %>
  digitalocean_access_token: <%= ENV['DIGITAL_OCEAN_ACCESS_TOKEN'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: centos-5.8
  driver_plugin: digitalocean
  driver_config:
    size: 1gb
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    image: centos-5-8-x64
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

- name: centos-6.5
  driver_plugin: digitalocean
  driver_config:
    size: 1gb
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    image: centos-6-5-x64
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

- name: fedora-21
  driver_plugin: digitalocean
  driver_config:
    size: 1gb
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    image: fedora-21-x64
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>
  attributes:
    java:
      jdk_version: 8

suites:
- name: server
  run_list:
  - recipe[sauceconnect::server]
  attributes: {}
